name: CI

on:
  push:
    branches: [ develop ]
  pull_request:
    branches: [ develop ]

jobs:
  lint:
    runs-on: ubuntu-latest
    container:
      image: golang:1.22
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run golangci-lint
        uses: golangci/golangci-lint-action@v6
        with:
          version: v1.60
          working-directory: src

  analyze:
    runs-on: ubuntu-latest
    container:
      image: golang:1.22
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run gocyclo Analysis
        uses: ./.github/actions/gocyclo-analysis
        id: gocyclo_analysis
        with:
          ignore_pattern: '_test|_mock|mock_|.pb.go|proto'
          over: '20'
          top: '10'
          working-directory: src

      - name: Post Results
        uses: marocchino/sticky-pull-request-comment@v2
        with:
          recreate: true
          header: gocyclo Report
          message: |
            ${{ env.gocyclo_report }}

  build:
    runs-on: ubuntu-latest
    container:
      image: golang:1.22
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build project
        run: make build
        working-directory: src

  test:
    runs-on: ubuntu-latest
    container:
      image: golang:1.22
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run tests
        run: make test
        working-directory: src
