name: CI

on:
  push:
    branches: [ develop ]
  pull_request:
    branches: [ develop ]

jobs:
  lint:
    runs-on: ubuntu-latest
    container:
      image: golang:1.22
      env:
        GOFLAGS: "-buildvcs=false" # fix issue with golangci-lint and vcs
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run golangci-lint
        uses: golangci/golangci-lint-action@v6
        with:
          version: v1.60
          working-directory: src
          skip-cache: true

  build:
    runs-on: ubuntu-latest
    container:
      image: golang:1.22
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build project
        run: make build
        working-directory: src

  test:
    runs-on: ubuntu-latest
    container:
      image: golang:1.22
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run tests
        run: make test
        working-directory: src
